[2m2022-10-28T16:02:13.554487Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task Tag("SendDotfilesLineCountTelemetry"): telemetry is disabled
[2m2022-10-28T16:05:42.679221Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: P2024", status: 500, sentry_id: Some("4808b7e57e1f4b478bc01713dc8d852c") })
[2m2022-10-28T16:05:42.679260Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: P2024
[2m2022-10-28T16:05:42.703829Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: P2024", status: 500, sentry_id: Some("6ab3a7c5df3b41a8bf5fa9a60092cf8c") })
[2m2022-10-28T16:05:42.703876Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: P2024
[2m2022-10-28T16:05:42.713703Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: P2024", status: 500, sentry_id: Some("e29a35f378284a60a49e3280b1890552") })
[2m2022-10-28T16:05:42.713774Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: P2024
[2m2022-10-28T16:05:42.734623Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: P2024", status: 500, sentry_id: Some("a425fad5fd8e445da27e917e72c5d5f9") })
[2m2022-10-28T16:05:42.734663Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: P2024
[2m2022-10-28T16:05:42.757379Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: P2024", status: 500, sentry_id: Some("750979d67ef74df4ac1b176306b1bf42") })
[2m2022-10-28T16:05:42.757441Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: P2024
[2m2022-10-28T16:05:42.777848Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: P2024", status: 500, sentry_id: Some("f976d43604d04fee8da33f53765d647b") })
[2m2022-10-28T16:05:42.777905Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: P2024
[2m2022-10-28T16:10:55.123348Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: [object Object]", status: 500, sentry_id: Some("db75d0db46f34e358b1d0d8fd054b945") })
[2m2022-10-28T16:10:55.123422Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: [object Object]
[2m2022-10-28T16:10:56.606946Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: [object Object]", status: 500, sentry_id: Some("a8accbd64183436f89c8b01ae0f23d2c") })
[2m2022-10-28T16:10:56.607012Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: [object Object]
[2m2022-10-28T16:18:17.235096Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: PrismaClientUnknownRequestError", status: 500, sentry_id: Some("82f52931d5a54194a46f5d3b14669675") })
[2m2022-10-28T16:18:17.235134Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: PrismaClientUnknownRequestError
[2m2022-10-28T16:18:27.927034Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: PrismaClientUnknownRequestError", status: 500, sentry_id: Some("9a4c0e7942944378854f297ef41fbca2") })
[2m2022-10-28T16:18:27.927105Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: PrismaClientUnknownRequestError
[2m2022-10-28T16:18:28.344596Z[0m [31mERROR[0m [2mfig_sync::dotfiles[0m[2m:[0m [2m52:[0m Could not sync dotfiles: Request(Fig { error: "Unexpected Server Error: PrismaClientUnknownRequestError", status: 500, sentry_id: Some("a72a89f0198f4e288fcac8a08805abd0") })
[2m2022-10-28T16:18:28.344655Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task SyncDotfiles: Unexpected Server Error: PrismaClientUnknownRequestError
[2m2022-10-28T16:20:54.871492Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task Tag("SendQueuedTelemetryEvents"): telemetry is disabled
[2m2022-10-28T16:22:15.734364Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mConnection refused (os error 61) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-28T16:22:15.734426Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: Connection refused (os error 61)
[2m2022-10-28T16:22:15.734476Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mConnection refused (os error 61) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-28T16:22:15.734484Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: Connection refused (os error 61)
[2m2022-10-28T16:22:15.734526Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mConnection refused (os error 61) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-28T16:22:15.734537Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: Connection refused (os error 61)
[2m2022-10-28T16:22:15.734570Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mConnection refused (os error 61) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-28T16:22:15.734591Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: Connection refused (os error 61)
[2m2022-10-28T16:22:31.658320Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task Tag("SendDotfilesLineCountTelemetry"): telemetry is disabled
[2m2022-10-28T16:32:01.827002Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
[2m2022-10-28T16:32:01.827143Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
[2m2022-10-28T16:32:02.095204Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m163:[0m Error while connecting to websocket: error sending request for url (https://api.fig.io/authenticate/ticket?os=macos&arch=x86_64&cliVersion=2.5.3&manifestVersion=1.0.62%2B542&deviceId=6d19400ddf382741976d80d08eb41bac4e38db00d23725543ca0c14a77f71427%3Ateziovsky%40gmail.com): connection error: Connection reset by peer (os error 54)
[2m2022-10-28T20:22:08.604105Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-28T20:22:08.604163Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-28T20:42:06.663121Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task Tag("SendDotfilesLineCountTelemetry"): telemetry is disabled
[2m2022-10-28T20:58:19.120597Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-28T20:58:19.120738Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-28T21:47:16.545448Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-28T21:47:16.545492Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-28T21:55:12.391650Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
[2m2022-10-28T21:55:12.391709Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })
[2m2022-10-29T02:53:12.647159Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-29T02:53:12.647195Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-29T04:53:22.665834Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m163:[0m Error while connecting to websocket: error sending request for url (https://api.fig.io/authenticate/ticket?os=macos&arch=x86_64&cliVersion=2.5.3&manifestVersion=1.0.62%2B542&deviceId=6d19400ddf382741976d80d08eb41bac4e38db00d23725543ca0c14a77f71427%3Ateziovsky%40gmail.com): connection error: Operation timed out (os error 60)
[2m2022-10-29T07:16:29.369838Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-29T07:16:29.369882Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-29T07:16:48.560756Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m163:[0m Error while connecting to websocket: error sending request for url (https://api.fig.io/authenticate/ticket?os=macos&arch=x86_64&cliVersion=2.5.3&manifestVersion=1.0.62%2B542&deviceId=6d19400ddf382741976d80d08eb41bac4e38db00d23725543ca0c14a77f71427%3Ateziovsky%40gmail.com): connection error: Operation timed out (os error 60)
[2m2022-10-29T07:32:28.485282Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mNo such file or directory (os error 2) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-29T07:32:28.485350Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: No such file or directory (os error 2)
[2m2022-10-29T07:32:28.485438Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mNo such file or directory (os error 2) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-29T07:32:28.485451Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: No such file or directory (os error 2)
[2m2022-10-29T07:32:28.485481Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mNo such file or directory (os error 2) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-29T07:32:28.485487Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: No such file or directory (os error 2)
[2m2022-10-29T07:32:28.485515Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mNo such file or directory (os error 2) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-29T07:32:28.485523Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: No such file or directory (os error 2)
[2m2022-10-29T07:51:46.336334Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task Tag("SendQueuedTelemetryEvents"): telemetry is disabled
[2m2022-10-29T09:16:51.243569Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-29T09:16:51.243648Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-29T13:22:00.828235Z[0m [31mERROR[0m [2mfig_cli::daemon::websocket[0m[2m:[0m [2m280:[0m Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-29T13:22:00.828314Z[0m [31mERROR[0m [2mfig_cli::daemon[0m[2m:[0m [2m145:[0m Error while processing websocket message: Websock next error: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })
[2m2022-10-29T14:41:55.381106Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mConnection refused (os error 61) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-29T14:41:55.381168Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: Connection refused (os error 61)
[2m2022-10-29T14:41:55.381214Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mConnection refused (os error 61) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-29T14:41:55.381221Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: Connection refused (os error 61)
[2m2022-10-29T14:41:55.381251Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mConnection refused (os error 61) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-29T14:41:55.381259Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: Connection refused (os error 61)
[2m2022-10-29T14:41:55.381292Z[0m [31mERROR[0m [2mfig_ipc::unix_socket[0m[2m:[0m [2m21:[0m Failed to connect [3merr[0m[2m=[0mConnection refused (os error 61) [3msocket[0m[2m=[0m"/var/tmp/fig/kuba/fig.socket"
[2m2022-10-29T14:41:55.381306Z[0m [31mERROR[0m [2mfig_cli::daemon::settings_watcher[0m[2m:[0m [2m153:[0m Failed to send hook: Connection refused (os error 61)
[2m2022-10-29T14:42:29.728803Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task Tag("SendDotfilesLineCountTelemetry"): telemetry is disabled
[2m2022-10-29T15:04:41.412609Z[0m [31mERROR[0m [2mfig_cli::daemon::scheduler[0m[2m:[0m [2m166:[0m Error running task Tag("SendQueuedTelemetryEvents"): telemetry is disabled
